- title: Alt-Balaji
  image: /images/alt-balaji.png
  description: AltBalaji tied up with Eko in July 2019 to help expand their penetration, especially in the LMI segment. These customers who have viewing habits in line with their digitally abled peers in tier 1 and tier 2 cities were able to leverage Eko’s 150,000 strong merchant network to be assisted with their app downloads as well as pay for their subscription in cash.

- title: Edelweiss
  image: /images/edelweiss.png
  description: With non life insurance products having a less than 1% pan-India penetration, Edelweiss products. Our merchants are helping Edelweiss expand their insurance base as well as helping the underinsured get more coverage. 
 
- title: Shopclues
  image: /images/shopclues.jpeg
  description: Shopclues identified Eko’s physical network as an important opportunity in the assisted commerce space. Our merchants, who tend to be digitally savvy as well as adept at using our proprietary platform ‘Connect’, help the end customer with relevant products. This mutually beneficial relationship forms an additional revenue source for our retailers as well as help Shopclues with their tier 3,4,5 expansion.

- title: test1
  image: /images/alt-balaji.png
  description: AltBalaji tied up with Eko in July 2019 to help expand their penetration, especially in the LMI segment. These customers who have viewing habits in line with their digitally abled peers in tier 1 and tier 2 cities were able to leverage Eko’s 150,000 strong merchant network to be assisted with their app downloads as well as pay for their subscription in cash.

- title: test2
  image: /images/alt-balaji.png
  description: AltBalaji tied up with Eko in July 2019 to help expand their penetration, especially in the LMI segment. These customers who have viewing habits in line with their digitally abled peers in tier 1 and tier 2 cities were able to leverage Eko’s 150,000 strong merchant network to be assisted with their app downloads as well as pay for their subscription in cash.

- title: test3
  image: /images/alt-balaji.png
  description: AltBalaji tied up with Eko in July 2019 to help expand their penetration, especially in the LMI segment. These customers who have viewing habits in line with their digitally abled peers in tier 1 and tier 2 cities were able to leverage Eko’s 150,000 strong merchant network to be assisted with their app downloads as well as pay for their subscription in cash.

- title: test4
  image: /images/alt-balaji.png
  description: AltBalaji tied up with Eko in July 2019 to help expand their penetration, especially in the LMI segment. These customers who have viewing habits in line with their digitally abled peers in tier 1 and tier 2 cities were able to leverage Eko’s 150,000 strong merchant network to be assisted with their app downloads as well as pay for their subscription in cash.

- title: test5
  image: /images/alt-balaji.png
  description: AltBalaji tied up with Eko in July 2019 to help expand their penetration, especially in the LMI segment. These customers who have viewing habits in line with their digitally abled peers in tier 1 and tier 2 cities were able to leverage Eko’s 150,000 strong merchant network to be assisted with their app downloads as well as pay for their subscription in cash.

- title: test6
  image: /images/alt-balaji.png
  description: AltBalaji tied up with Eko in July 2019 to help expand their penetration, especially in the LMI segment. These customers who have viewing habits in line with their digitally abled peers in tier 1 and tier 2 cities were able to leverage Eko’s 150,000 strong merchant network to be assisted with their app downloads as well as pay for their subscription in cash.
